version: '3'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"   
      - "9000:9000"  
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  clickhouse-data:
